-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 14, 2022 at 10:28 AM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `iir_uas`
--

-- --------------------------------------------------------

--
-- Table structure for table `crawl`
--

CREATE TABLE `crawl` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `link` text NOT NULL,
  `cite` int(11) NOT NULL,
  `keyword` varchar(255) NOT NULL,
  `crawled` enum('NOT YET','FAIL','SUCCESS') NOT NULL DEFAULT 'NOT YET'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `crawl`
--

INSERT INTO `crawl` (`id`, `title`, `link`, `cite`, `keyword`, `crawled`) VALUES
(1, 'Justice, health, and healthcare', 'https://www.tandfonline.com/doi/abs/10.1162/152651601300168834', 599, 'healthcare', 'SUCCESS'),
(2, 'An overview of the healthcare system in Taiwan', 'https://www.tandfonline.com/doi/abs/10.1080/17571472.2010.11493315', 317, 'healthcare', 'SUCCESS'),
(3, 'Operations research in healthcare: a survey', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1475-3995.2010.00767.x', 452, 'healthcare', 'NOT YET'),
(4, 'Overview of healthcare in the UK', 'https://link.springer.com/article/10.1007/s13167-010-0050-1', 91, 'healthcare', 'NOT YET'),
(5, 'An overview of GeoAI applications in health and healthcare', 'https://link.springer.com/article/10.1186/s12942-019-0171-2', 89, 'healthcare', 'NOT YET'),
(6, 'Testing treatments: better research for better healthcare', 'https://books.google.com/books?hl=en&amp;lr=&amp;id=dncmUN-yo0MC&amp;oi=fnd&amp;pg=PR6&amp;dq=healthcare&amp;ots=L9TBruNUHs&amp;sig=jv7R1f2U1zfdvxL07YPKiwcGxHo', 298, 'healthcare', 'NOT YET'),
(7, 'Technology and the future of healthcare', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4147743/', 235, 'healthcare', 'SUCCESS'),
(8, 'Impaired healthcare professional', 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.423.1845&amp;rep=rep1&amp;type=pdf', 346, 'healthcare', 'NOT YET'),
(9, 'The healthcare cost and utilization project: an overview.', 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.548.9070&amp;rep=rep1&amp;type=pdf', 478, 'healthcare', 'NOT YET'),
(10, 'Data mining in healthcare&#8211;a review', 'https://www.sciencedirect.com/science/article/pii/S1877050915036066', 311, 'healthcare', 'SUCCESS'),
(11, 'A decade&#39;s perspective on DNA sequencing technology', 'https://www.nature.com/articles/nature09796', 1122, 'technology', 'NOT YET'),
(12, 'Photovoltaics: technology overview', 'https://www.sciencedirect.com/science/article/pii/S0301421500000860', 306, 'technology', 'SUCCESS'),
(13, 'Nanocapsule technology: a review', 'https://www.dl.begellhouse.com/journals/3667c4ae6e8fd136,13237f906e958e8d,12624a520b8f6730.html', 747, 'technology', 'NOT YET'),
(14, 'IPL technology: a review', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/lsm.10145', 374, 'technology', 'NOT YET'),
(15, 'The market for technology', 'https://www.sciencedirect.com/science/article/pii/S0169721810010154', 510, 'technology', 'NOT YET'),
(16, 'An overview of the HomePlug AV2 technology', 'https://www.hindawi.com/journals/JECE/2013/892628/', 103, 'technology', 'SUCCESS'),
(17, 'Bio-Rad&#39;s Bio-Plex? suspension array system, xMAP technology overview', 'https://www.tandfonline.com/doi/abs/10.3109/13813455.2012.705301', 205, 'technology', 'SUCCESS'),
(18, 'dPCR: a technology review', 'https://www.mdpi.com/284580', 325, 'technology', 'NOT YET'),
(19, 'A review of robocasting technology', 'https://www.cambridge.org/core/journals/mrs-online-proceedings-library-archive/article/review-of-robocasting-technology/5A182C696B3BCAC9F05644FD5DB5E122', 163, 'technology', 'SUCCESS'),
(20, 'DMFCs: from fundamental aspects to technology development', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/1615-6854(200107)1:2%3C133::AID-FUCE133%3E3.0.CO;2-5', 1763, 'technology', 'NOT YET'),
(21, 'The evolution of robotics research', 'https://ieeexplore.ieee.org/abstract/document/4141037/', 422, 'robotics', 'NOT YET'),
(22, 'Social robotics', 'https://link.springer.com/chapter/10.1007/978-3-319-32552-1_72', 200, 'robotics', 'NOT YET'),
(23, 'Robotics for surgery', 'https://www.biorobotics.harvard.edu/pubs/1990/howe_ARBE1990.pdf', 419, 'robotics', 'NOT YET'),
(24, 'Robotics for medical applications', 'https://ieeexplore.ieee.org/abstract/document/540149/', 271, 'robotics', 'NOT YET'),
(25, 'A review of robotics in surgery', 'https://journals.sagepub.com/doi/abs/10.1243/0954411001535309', 500, 'robotics', 'NOT YET'),
(26, 'Healthcare robotics', 'https://dl.acm.org/doi/fullHtml/10.1145/3127874', 200, 'robotics', 'NOT YET'),
(27, 'Probabilistic algorithms in robotics', 'https://ojs.aaai.org/index.php/aimagazine/article/view/1534', 703, 'robotics', 'NOT YET'),
(28, 'Soft robotics', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.201800907', 377, 'robotics', 'NOT YET'),
(29, 'What does robotics offer animal behaviour?', 'https://www.sciencedirect.com/science/article/pii/S0003347200915148', 284, 'robotics', 'SUCCESS'),
(30, 'The grand challenges of Science Robotics', 'https://www.science.org/doi/abs/10.1126/scirobotics.aar7650', 688, 'robotics', 'NOT YET'),
(31, 'Plant argonautes', 'https://www.sciencedirect.com/science/article/pii/S1360138508001386', 702, 'plant', 'SUCCESS'),
(32, 'Plant cyclopeptides', 'https://pubs.acs.org/doi/full/10.1021/cr040699h', 425, 'plant', 'NOT YET'),
(33, 'Plant phospholipases', 'https://www.researchgate.net/profile/Xuemin-Wang-4/publication/12000490_Plant_Phospholipases/links/56a7a1ba08ae0fd8b3fe16f8/Plant-Phospholipases.pdf', 349, 'plant', 'NOT YET'),
(34, 'Plant&#8211;plant interactions and environmental change', 'https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8137.2006.01752.x', 568, 'plant', 'NOT YET'),
(35, 'Plant cystatins', 'https://www.sciencedirect.com/science/article/pii/S0300908410002208', 207, 'plant', 'SUCCESS'),
(36, 'The epigenome and plant development', 'https://www.researchgate.net/profile/Guangming-He-3/publication/50865195_The_Epigenome_and_Plant_Development/links/0f317537403292218a000000/The-Epigenome-and-Plant-Development.pdf', 181, 'plant', 'NOT YET'),
(37, 'What happened to plant caspases?', 'https://academic.oup.com/jxb/article-abstract/59/3/491/577850', 229, 'plant', 'SUCCESS'),
(38, 'Towards plant pangenomics', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/pbi.12499', 157, 'plant', 'NOT YET'),
(39, 'Plant molluscicides', 'https://www.thieme-connect.com/products/ejournals/pdf/10.1055/s-2007-971215.pdf', 165, 'plant', 'NOT YET'),
(40, 'The plant sulfolipid', 'https://www.sciencedirect.com/science/article/pii/B9781483199375500168', 202, 'plant', 'SUCCESS'),
(41, 'Thoracic imaging tests for the diagnosis of COVID&#8208;19', 'https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD013639.pub4/abstract', 171, 'covid', 'SUCCESS'),
(42, 'Clinical presentation of COVID-19: case series and review of the literature', 'https://www.mdpi.com/768822', 58, 'covid', 'NOT YET'),
(43, 'An overview of COVID-19', 'https://link.springer.com/article/10.1631/jzus.B2000083', 321, 'covid', 'NOT YET'),
(44, 'COVID-19 and multiorgan response', 'https://www.sciencedirect.com/science/article/pii/S0146280620300955', 848, 'covid', 'SUCCESS'),
(45, 'Signs and symptoms to determine if a patient presenting in primary care or hospital outpatient settings has COVID&#8208;19', 'https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD013665.pub2/abstract', 449, 'covid', 'SUCCESS'),
(46, 'Routine laboratory testing to determine if a patient has COVID&#8208;19', 'https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD013787/abstract', 49, 'covid', 'SUCCESS'),
(47, 'Environmental perspective of COVID-19', 'https://www.sciencedirect.com/science/article/pii/S0048969720323871', 666, 'covid', 'SUCCESS'),
(48, 'Modelling covid-19', 'https://www.nature.com/articles/s42254-020-0178-4', 137, 'covid', 'NOT YET'),
(49, 'Treatment for COVID-19: An overview', 'https://www.sciencedirect.com/science/article/pii/S0014299920307366', 171, 'covid', 'SUCCESS'),
(50, 'Role of favipiravir in the treatment of COVID-19', 'https://www.sciencedirect.com/science/article/pii/S1201971220322736', 200, 'covid', 'SUCCESS'),
(51, 'Climate change and marine plankton', 'https://www.sciencedirect.com/science/article/pii/S0169534705000650', 1311, 'plankton', 'SUCCESS'),
(52, 'Marine plankton food chains', 'https://www.jstor.org/stable/2097146', 534, 'plankton', 'SUCCESS'),
(53, 'von Liebig&#39;s law of the minimum and plankton ecology (1899&#8211;1991)', 'https://www.sciencedirect.com/science/article/pii/0079661194900221', 287, 'plankton', 'NOT YET'),
(54, 'The Continuous Plankton Recorder: concepts and history, from Plankton Indicator to undulating recorders', 'https://www.sciencedirect.com/science/article/pii/S0079661103001277', 309, 'plankton', 'NOT YET'),
(55, 'Beyond the Plankton Ecology Group(PEG) Model: Mechanisms Driving Plankton Succession', 'https://www.academia.edu/download/41875964/Beyond_the_Plankton_Ecology_Group_PEG_20160201-19414-19f82o1.pdf', 578, 'plankton', 'NOT YET'),
(56, 'The structure and evolution of plankton communities', 'https://www.sciencedirect.com/science/article/pii/0079661185900369', 219, 'plankton', 'SUCCESS'),
(57, 'Microdistribution of plankton', 'http://www.vliz.be/nl/imis?module=ref&amp;refid=8385&amp;page&amp;basketaction=add', 380, 'plankton', 'NOT YET'),
(58, 'The peril of the plankton', 'https://academic.oup.com/icb/article-abstract/50/4/552/647672', 73, 'plankton', 'SUCCESS'),
(59, 'Towards a resolution of &#39;the paradox of the plankton&#39;: A brief overview of the proposed mechanisms', 'https://www.sciencedirect.com/science/article/pii/S1476945X07000165', 163, 'plankton', 'SUCCESS'),
(60, 'Plankton in the open Mediterranean Sea: a review', 'https://bg.copernicus.org/articles/7/1543/2010/', 536, 'plankton', 'NOT YET');

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE `data` (
  `id` int(11) NOT NULL,
  `title` varchar(2000) NOT NULL,
  `number_citations` int(200) NOT NULL,
  `authors` varchar(2000) NOT NULL,
  `abstract` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`id`, `title`, `number_citations`, `authors`, `abstract`) VALUES
(1, 'Information Technology and Corporate Strategy: A Research Perspective', 1153, 'J. Yannis Bakos and Michael E. Treacy', 'The use of information technology (IT) as a competitive weapon has become a popular cliche; but there is still a marked lack of understanding of the issues that determine the influence of information technology on a particular organization and the processes that will allow a smooth coordination of technology and corporate strategy. This article surveys the major efforts to arrive at a relevent framework, and attempts to integrate them in a more comprehensive viewpoint. The focus then turns to the major research issues in understanding the impact of information technology on competitive strategy.'),
(2, 'The role of information technology in the organization: a review, model, and assessment', 1249, 'Todd Dewetta & Gareth RJonesa', 'This paper reviews and extends recent scholarly and popular literature to provide a broad overview of how information technology (IT) impacts organizational characteristics and outcomes. First, based on a review of the literature, we describe two of the principal performance enhancing benefits of IT: information efficiencies and information synergies, and identify five main organizational outcomes of the application of IT that embody these benefits. We then discuss the role that IT plays in moderating the relationship between organizational characteristics including structure, size, learning, culture, and interorganizational relationships and the most strategic outcomes, organizational efficiency and innovation. Throughout we discuss the limitations and possible negative consequences of the use of IT and close by considering several key areas for future research.'),
(3, 'Information Technology and Productivity: A Review of the Literature', 1085, 'Erik Brynjolfsson & Shinkyu Yang', 'In recent years, the relationship between information technology (IT) and productivity has become a source of debate. In the 1980s and early 1990s, empirical research on IT productivity generally did not identify significant productivity improvements. More recently, as new data are identified and more sophisticated methodologies are applied, several researchers have found evidence that IT is associated not only with improvement in productivity, but also in intermediate measures, consumer surplus, and economic growth. Nonetheless, new questions emerge as old puzzles fade. This survey reviews the literature, identifies remaining questions, and concludes with recommendations for applications of traditional methodologies to new data sources, as well as alternative, broader metrics of welfare to assess and enhance the benefits of IT.'),
(4, 'The Use of Information Technology to Enhance Management School Education: A Theoretical View', 1723, 'Dorothy E. Leidner and Sirkka L. Jarvenpaa', 'To use information technology to improve learning processes, the pedagogical assumptions underlying the design of information technology for educational purposes must be understood. This paper reviews different models of learning, surfaces assumptions of electronic teaching technology, and relates those assumptions to the differing models of learning. Our analysis suggests that initial attempts to bring information technology to management education follow a classic story of automating rather than transforming. IT is primarily used to automate the information delivery function in classrooms. In the absence of fundamental changes to the teaching and learning process, such classrooms may do little but speed up ineffective processes and methods of teaching. Our mapping of technologies to learning models identifies sets of technologies in which management schools should invest in order to informate up and down and ultimately transform the educational environment and processes. For researchers interested in the use of information technology to improve learning processes, the paper provides a theoretical foundation for future work.'),
(5, 'Research on information technology in the hospitality industry', 288, 'Peter O’ Connor & Jamie Murphy', 'This paper reviews recent research on information technology in the hospitality industry. The analysis revealed three broad research areas: the Internet\'s effects on distribution; on pricing; and on consumer interactions. Similar to aftermath of the dot com boom, the hospitality industry is realising that the information technology has unintended effects and prognosticators are often wrong. While the reviewed articles provide sound advice for hospitality operators and a rich stream of future research for academics, poor rigor and a lack of relevance throughout the reviewed journals underscore a worrying trend in hospitality research.'),
(6, 'User Acceptance of Information Technology: Theories and Models\r\n', 1363, 'Andrew Dillon & Michael G. Morris', 'Reviews literature in user acceptance and resistance to information technology design and implementation. Examines innovation diffusion, technology design and implementation, human-computer interaction, and information systems. Concentrates on the determinants of user acceptance and resistance and emphasizes how researchers and developers can predict levels of user acceptance. (Contains 126 references.) (PEN)'),
(7, 'Past, present & future of information technology in pedometrics', 47, 'David G.Rossiter', 'Although pedometric approaches were taken as early as 1925, the post-WWII development of information technology radically transformed the possibilities for applying mathematical methods to soil science. The most significant development is the digital computer and associated developments in computer science. These allowed statistical inference on large pedometric datasets, e.g., numerical taxonomy of soils from the early 1960s and geostatistics from the mid-1970s, as well as simulation models of soil processes. By the time of the first Pedometrics conference in 1992 sufficient computing power was available for stochastic simulation and complex geostatistical procedures such as disjunctive kriging. In the intervening 25 years computing power has grown to almost magical proportions, allowing individual scientists to carry out complex procedures. A second development is the growth of networking. This facilitates collaboration among pedometricians, rapid communication with journals, collaborative programming and publication, and easy access to resources. A third development is the availability of on-line storage of large datasets, especially of open data, including GIS coverages and remotely-sensed images. This allows pedometricians working on geographic problems to integrate sources from multiple disciplines, most notably in digital soil mapping using a wide variety of covariates related to soil genesis. It also promotes the an open-source movement of collaborative development of computer programs useful for pedometrics. A fourth development is the wide range of digital sensors which provide data for pedometrics; sensors include spectroscopy, electromagnetic induction, and γ-ray detectors., connected to each other and to central data stores. A fifth development is wireless technology, including mobile computing and telephony, again greatly facilitating rapid and extensive data collection – in pedometrics, the more dense the data, the greater the analytical possibilities and the lower the uncertainty. A final development is a global navigation satellite system (e.g., GPS), making accurate georeference of field data a routine part of data collection, and thereby assuring the highest possible accuracy in maps made by predictive pedometric methods. As computer power increases, models can be correspondingly detailed. As sensor networks and remote sensing provide ever more abundant and spatiotemporally fine-resolution measurements, the challenge is to manage this information and maintain the link with pedologic and soil-landscape knowledge, within the context of societal needs for the results of pedometric analysis.'),
(8, 'Information Technology Diffusion: A Review of\r\nEmpirical Research\r\n', 974, 'Robert G. Fichman', 'Innovation diffusion theory provides a useful perspective on one of the most persistently challenging topics in the IT\r\nfield, namely, how to improve technology assessment, adoption and implementation. For this reason, diffusion is\r\ngrowing in popularity as a reference theory for empirical studies of information technology adoption and diffusion,\r\nalthough no comprehensive review of this body of work has been published to date. This paper presents the results\r\nof a critical review of eighteen empirical studies published during the period 1981-1991. Conclusive results were\r\nmost likely when the adoption context closely matched the contexts in which classical diffusion theory was\r\ndeveloped (for example, individual adoption of personal-use technologies), or when researchers extended diffusion\r\ntheory to account for new factors specific to the IT adoption context under study.\r\nBased on classical diffusion theory and other recent conceptual work, a framework is developed to guide future\r\nresearch in IT diffusion. The framework maps two classes of technology (ones that conform closely to classical\r\ndiffusion assumptions versus ones that do not) against locus of adoption (individual versus organizational), resulting\r\nin four IT adoption contexts. For each adoption context, variables impacting adoption and diffusion are identified.\r\nAdditionally, directions for future research are discussed.'),
(11, 'Why do people use information technology? A critical review of the technology acceptance model', 5859, 'Paul Legris  ,John Ingham & Pierre Collerette', 'Information systems (IS) implementation is costly and has a relatively low success rate. Since the seventies, IS research has contributed to a better understanding of this process and its outcomes. The early efforts concentrated on the identification of factors that facilitated IS use. This produced a long list of items that proved to be of little practical value. It became obvious that, for practical reasons, the factors had to be grouped into a model in a way that would facilitate analysis of IS use.\r\n\r\nIn 1985, Fred Davis suggested the technology acceptance model (TAM). It examines the mediating role of perceived ease of use and perceived usefulness in their relation between systems characteristics (external variables) and the probability of system use (an indicator of system success). More recently, Davis proposed a new version of his model: TAM2. It includes subjective norms, and was tested with longitudinal research designs. Overall the two explain about 40% of system’s use. Analysis of empirical research using TAM shows that results are not totally consistent or clear. This suggests that significant factors are not included in the models.\r\n\r\nWe conclude that TAM is a useful model, but has to be integrated into a broader one which would include variables related to both human and social change processes, and to the adoption of the innovation model.'),
(12, 'Measuring the costs and benefits of information technology in construction', 170, 'ROGER FLANAGAN & LAURENCE MARSH', 'Information technology (IT) has been widely applied across many economic sectors in order to increase competitiveness and reduce costs. This paper identifies that uptake of IT within construction is low. It is argued that significant barriers preventing construction organizations from investing in IT include uncertainty concerning the identification and measurement of benefits associated with applications. In particular, it is argued that difficulties in quantifying benefits associated with improved information availability and decision making prevent effective IT cost/benefit analysis. Existing approaches to evaluating IT within construction are reviewed. A framework is presented which identifies metrics by which IT impacts both management and operational processes within construction in order to deliver value. An evaluation methodology tailored to one specific IT application, high‐density bar coding in maintenance management, is presented to illustrate the quantification of both the costs and benefits of applying IT.'),
(13, 'Information technology and systems justification: A review for research and applications', 342, 'A.Gunasekaran ,E.W.T.Ngai & R.E.McGaughey', 'Information technology (IT) such as Electronic Data Interchange (EDI), Radio Frequency Identification Technology (RFID), wireless, the Internet and World Wide Web (WWW), and Information Systems (IS) such as Electronic Commerce (E-Commerce) systems and Enterprise Resource Planning (ERP) systems have had tremendous impact in education, healthcare, manufacturing, transportation, retailing, pure services, and even war. Many organizations turned to IT/IS to help them achieve their goals; however, many failed to achieve the full potential of IT/IS. These failures can be attributed at least in part to a weak link in the planning process. That weak link is the IT/IS justification process. The decision-making process has only grown more difficult in recent years with the increased complexity of business brought about by the rapid growth of supply chain management, the virtual enterprise and E-business. These are but three of the many changes in the business environment over the past 10–12 years. The complexities of this dynamic new business environment should be taken into account in IT/IS justification. We conducted a review of the current literature on IT/IS justification. The purpose of the literature review was to assemble meaningful information for the development of a framework for IT/IS evaluation that better reflects the new business environment. A suitable classification scheme has been proposed for organizing the literature reviewed. Directions for future research are indicated.\r\n\r\n'),
(14, 'Recent applications of economic theory in information Technology research', 301, 'J.Yannis Bakos & Chris F.Kemerer', 'Academicians and practitioners are becoming increasingly interested in the economics of Information Technology (IT). In part, this interest stems from the increased role that IT now plays in the strategic thinking of most large organizations, and from the significant dollar costs expended by these organizations on IT. Naturally enough, researchers are turning to economics as a reference discipline in their attempt to answer questions concerning both the value added by IT and the true cost of providing IT resources. This increased interest in the economics of IT is manifested in the application of a number of aspects of economic theory in recent information systems research, leading to results that have appeared in a wide variety of publication outlets This article reviews this work and provides a systematic categorization as a first step in establishing a common research tradition, and to serve as an introduction for researchers beginning work in this area. Six areas of economic theory are represented: Information economics, production economics, economic models of organizational performance, industrial organization, institutional economics (agency theory and transaction cost theory), and macroeconomic studies of IT impact. For each of these areas, recent work is reviewed and suggestions for future research are provided.\r\n\r\n'),
(15, 'Literature Review of Information Technology Adoption Models at Firm Level\r\n', 1743, 'Tiago Oliveira & Maria Fraga Martins', 'Today, information technology (IT) is universally regarded as an essential tool in enhancing the competitiveness of the economy of a country. There is consensus that IT has significant effects on the productivity of firms. These effects will only be realized if, and when, IT are widely spread and used. It is essential to understand the determinants of IT adoption. Consequently it is necessary to know the theoretical models. There are few reviews in the literature about the comparison of IT adoption models at the individual level, and to the best of our knowledge there are even fewer at the firm level. This review will fill this gap. In this study, we review theories for adoption models at the firm level used in information systems literature and discuss two prominent models: diffusion on innovation (DOI) theory, and the technology, organization, and environment (TOE) framework. The DOI found that individual characteristics, internal characteristics of organizational structure, and external characteristics of the organization are important antecedents to organizational innovativeness. The TOE framework identifies three aspects of an enterprise\'s context that influence the process by which it adopts and implements a technological innovation: technological context, organizational context, and environmental context. We made a thorough analysis of the TOE framework, analysing the studies that used only this theory and the studies that combine the TOE framework with other theories such as: DOI, institutional theory, and the Iacovou, Benbasat, and Dexter model. The institutional theory helps us to understand the factors that influence the adoption of interorganizational systems (IOSs); it postulates that mimetic, coercive, and normative institutional pressures existing in an institutionalized environment may influence the organization’s predisposition toward an IT‑based interorganizational system. The Iacovou, Benbasat, and Dexter model, analyses IOSs characteristics that influence firms to adopt IT innovations. It is based on three contexts: perceived benefits, organizational readiness, and external pressure. The analysis of these models takes into account the empirical literature, and the difference between independent and dependent variables. The paper also makes recommendations for future research.'),
(16, 'Using information technology to improve the management of chronic disease', 327, 'Branko G Celler PhD, Nigel H Lovell PhD , Jim Basilakis MB BS & Research Associate', 'Information and communications technology (ICT) is increasingly being used in management of chronic illness to facilitate shared services (virtual health networks and electronic health records), knowledge management (care rules and protocols, scheduling, information directories), as well as consumer-based health education and evidence-based clinical protocols.\r\nCommon applications of ICT include home monitoring of vital signs for patients with chronic disease, as well as replacing home visits by nurses in person with telemedicine videophone consultations.\r\nA patient-managed Home Telecare System with integrated clinical signs monitoring, automated scheduling and medication reminders, as well as access to health education and daily logs, is presented as an example of ICT use for chronic disease self-management.\r\nA clinical case study demonstrates how early identification of adverse trends in clinical signs recorded in the home can either avoid hospital readmission or reduce the length of hospital stay.'),
(17, 'Information technology in health promotion ', 91, 'T. P. Lintonen & A.I.Konu, D. Seedhouse', 'eHealth, the use of information technology to improve or enable health and health care, has recently been high on the health care development agenda. Given the vivid interest in eHealth, little reference has been made to the use of these technologies in the promotion of health. The aim of this present study was to conduct a review on recent uses of information technology in health promotion through looking at research articles published in peer-reviewed journals. Fifteen relevant journals with issues published between 2003 and June 2005 yielded altogether 1352 articles, 56 of which contained content related to the use of information technology in the context of health promotion. As reflected by this rather small proportion, research on the role of information technology is only starting to emerge. Four broad thematic application areas within health promotion were identified: use of information technology as an intervention medium, use of information technology as a research focus, use of information technology as a research instrument and use of information technology for professional development. In line with this rather instrumental focus, the concepts ‘ePromotion of Health’ or ‘Health ePromotion’ would come close to describing the role of information technology in health promotion.'),
(18, 'Smart City and information technology: A review', 165, 'Andrés Camero & Enrique Alba', 'Smart City is a recent concept that is gaining momentum in public opinion, and thus, it is making its way into the agendas of researchers and city authorities all over the world. However, there is no consensus of what exactly is a smart city, and academic research is, at best, building applications in numerous silos. This paper explores the computer science and information technology literature about Smart City. Using data analysis techniques, we contribute to present the domain from an objective data-based point of view, aiming to highlight its major trends, and providing a single entry point for newcomers.'),
(19, 'Accounting for the Contradictory Organizational Consequences of Information Technology: Theoretical Directions and Methodological Implications', 1084, 'Daniel Robey & Marie-Claude Boudreau', 'Although much contemporary thought considers advanced information technologies as either determinants or enablers of radical organizational change, empirical studies have revealed inconsistent findings to support the deterministic logic implicit in such arguments. This paper reviews the contradictory empirical findings both across studies and within studies, and proposes the use of theories employing a logic of opposition to study the organizational consequences of information technology. In contrast to a logic of determination, a logic of opposition explains organizational change by identifying forces both promoting change and impeding change. Four specific theories are considered: organizational politics, organizational culture, institutional theory, and organizational learning. Each theory is briefly described to illustrate its usefulness to the problem of explaining information technology\'s role in organizational change. Four methodological implications of using these theories are also discussed: empirical identification of opposing forces, statement of opposing hypotheses, process research, and employing multiple interpretations.'),
(21, 'Advances in the application of information technology to sport performance', 524, 'Dario G. Liebermann,Larry Katz,Mike D. Hughes,Roger M. Bartlett,Jim McClements &Ian M. Franks', 'This paper overviews the diverse information technologies that are used to provide athletes with relevant feedback. Examples taken from various sports are used to illustrate selected applications of technology-based feedback. Several feedback systems are discussed, including vision, audition and proprioception. Each technology described here is based on the assumption that feedback would eventually enhance skill acquisition and sport performance and, as such, its usefulness to athletes and coaches in training is critically evaluated.'),
(22, 'Improving Modern Cancer Care Through Information Technology', 157, 'Steven B.ClauserPhD Edward H.WagnerMD, MPH Erin J.Aiello Bowles MPH ,Leah Tuzzio MPH ,Sarah M.GreeneMPH', 'The cancer care system is increasingly complex, marked by multiple hand-offs between primary care and specialty providers, inadequate communication among providers, and lack of clarity about a “medical home” (the ideal accountable care provider) for cancer patients. Patients and families often cite such difficulties as information deficits, uncoordinated care, and insufficient psychosocial support. This article presents a review of the challenges of delivering well coordinated, patient-centered cancer care in a complex modern healthcare system. An examination is made of the potential role of information technology (IT) advances to help both providers and patients. Using the published literature as background, a review is provided of selected work that is underway to improve communication, coordination, and quality of care. Also discussed are additional challenges and opportunities to advancing understanding of how patient data, provider and patient involvement, and informatics innovations can support high-quality cancer care.');

-- --------------------------------------------------------

--
-- Table structure for table `journals`
--

CREATE TABLE `journals` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `link` text NOT NULL,
  `cite` int(11) NOT NULL,
  `keyword` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `journals`
--

INSERT INTO `journals` (`id`, `title`, `link`, `cite`, `keyword`) VALUES
(1, 'Present and future <b>robot </b>control development&#8212;An industrial perspective', 'https://www.sciencedirect.com/science/article/pii/S1367578807000077', 420, 'robot'),
(2, '<b>Robot </b>see, <b>robot </b>do: An overview of <b>robot </b>imitation', 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.27.292&amp;rep=rep1&amp;type=pdf', 258, 'robot'),
(3, 'Trends and challenges in <b>robot </b>manipulation', 'https://www.science.org/doi/abs/10.1126/science.aat8414', 197, 'robot'),
(4, '<b>Robot </b>programming', 'https://ieeexplore.ieee.org/abstract/document/1456949/', 469, 'robot'),
(5, 'Robovie: an interactive humanoid <b>robot</b>', 'https://www.emerald.com/insight/content/doi/10.1108/01439910110410051/full/html', 337, 'robot'),
(6, 'Current researches and future development trend of intelligent <b>robot</b>: A review', 'https://link.springer.com/article/10.1007/s11633-018-1115-1', 79, 'robot'),
(7, 'Kalman filter for <b>robot </b>vision: a survey', 'https://ieeexplore.ieee.org/abstract/document/5985520/', 525, 'robot'),
(8, 'Model learning for <b>robot </b>control: a survey', 'https://link.springer.com/article/10.1007/s10339-011-0404-1', 501, 'robot'),
(9, 'An overview of <b>robot </b>force control', 'https://www.cambridge.org/core/journals/robotica/article/an-overview-of-robot-force-control/403E8775F31C1162365B26C39FE557F4', 428, 'robot'),
(10, 'Mobile <b>robot </b>positioning: Sensors and techniques', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/(SICI)1097-4563(199704)14:4%3C231::AID-ROB2%3E3.0.CO;2-R', 1049, 'robot'),
(11, '<b>Plant </b>argonautes', 'https://www.sciencedirect.com/science/article/pii/S1360138508001386', 699, 'plant'),
(12, '<b>Plant</b>&#8211;<b>plant </b>interactions and environmental change', 'https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8137.2006.01752.x', 567, 'plant'),
(13, '<b>Plant </b>cyclopeptides', 'https://pubs.acs.org/doi/full/10.1021/cr040699h', 425, 'plant'),
(14, '<b>Plant </b>phospholipases', 'https://www.annualreviews.org/doi/abs/10.1146/annurev.arplant.52.1.211', 349, 'plant'),
(15, '<b>Plant </b>cystatins', 'https://www.sciencedirect.com/science/article/pii/S0300908410002208', 204, 'plant'),
(16, 'The epigenome and <b>plant </b>development', 'https://www.annualreviews.org/doi/abs/10.1146/annurev-arplant-042110-103806', 180, 'plant'),
(17, 'What happened to <b>plant </b>caspases?', 'https://academic.oup.com/jxb/article-abstract/59/3/491/577850', 228, 'plant'),
(18, 'Towards <b>plant </b>pangenomics', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/pbi.12499', 154, 'plant'),
(19, '<b>Plant </b>molluscicides', 'https://www.thieme-connect.com/products/ejournals/pdf/10.1055/s-2007-971215.pdf', 165, 'plant'),
(20, 'The <b>plant </b>sulfolipid', 'https://www.sciencedirect.com/science/article/pii/B9781483199375500168', 202, 'plant');

-- --------------------------------------------------------

--
-- Table structure for table `journal_data`
--

CREATE TABLE `journal_data` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `abstract` text NOT NULL,
  `authors` varchar(255) NOT NULL,
  `cite` int(11) NOT NULL,
  `crawl_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `journal_data`
--

INSERT INTO `journal_data` (`id`, `title`, `abstract`, `authors`, `cite`, `crawl_id`) VALUES
(1, 'Justice, health, and healthcare', 'Healthcare (including public health) is special because it protects normal functioning, which in turn protects the range of opportunities open to individuals. I extend this account in two ways. First, since the distribution of goods other than healthcare affect population health and its distribution, I claim that Rawls\'s principles of justice describe a fair distribution of the social determinants of health, giving a partial account of when health inequalities are unjust. Second, I supplement a principled account of justice for health and healthcare with an account of fair process for setting limits or rationing care. This account is provided by three conditions that comprise \"accountability for reasonableness.\"', '-', 599, 1),
(2, 'An overview of the healthcare system in Taiwan', 'Taiwan adopted a national health insurance system in 1995. It is a government administered insurancebased national healthcare system. Although, like the UK, Taiwan has a single payer system for healthcare, there are several differences between the two systems. The characteristics of the Taiwanese system include good accessibility, comprehensive population coverage, short waiting times, relatively low costs and a national health insurance databank for planning, monitoring and evaluating health services. The weaknesses include variable quality of care, a weak gatekeeper role and increasing financial pressures.', '-', 317, 2),
(3, 'Technology and the future of healthcare', 'Healthcare changes dramatically because of technological developments, from anesthetics and antibiotics to magnetic resonance imaging scanners and radiotherapy. Future technological innovation is going to keep transforming healthcare, yet while technologies (new drugs and treatments, new devices, new social media support for healthcare, etc) will drive innovation, human factors will remain one of the stable limitations of breakthroughs. No predictions can satisfy everybody; instead, this article explores fragments of the future to see how to think more clearly about how to get where we want to go.', '-', 235, 7),
(4, 'Data mining in healthcare&#8211;a review', 'The knowledge discovery in database (KDD) is alarmed with development of methods and techniques for making use of data. One of the most important step of the KDD is the data mining. Data mining is the process of pattern discovery and extraction where huge amount of data is involved. Both the data mining and healthcare industry have emerged some of reliable early detection systems and other various healthcare related systems from the clinical and diagnosis data. In regard to this emerge, we have reviewed the various paper involved in this field in terms of method, algorithms and results. This review paper has consolidated the papers reviewed inline to the disciplines, model, tasks and methods. Results and evaluation methods are discussed for selected papers and a summary of the finding is presented to conclude the paper.', '-', 311, 10),
(5, 'Photovoltaics: technology overview', 'Solar electricity produced by photovoltaic solar cells is one of the most promising options yet identified for sustainably providing the world&#x27;s future energy requirements. Although the technology has, in the past, been based on the same silicon wafers as used in microelectronics, a transition is in progress to a second generation of a potentially much lower-cost thin-film technology. Cost reductions from both increased manufacturing volume and such improved technology are expected to continue to drive down cell prices over the coming two decades to a level where the cells can provide competitively priced electricity on a large scale. The subsidised, urban residential rooftop application of photovoltaics is expected to provide the major application of the coming decade and to provide the market growth needed to reduce prices. Large centralised solar photovoltaic power stations able to provide low-cost electricity on a large scale would become increasingly attractive approaching 2020.', '-', 306, 12),
(6, 'An overview of the HomePlug AV2 technology', 'HomePlug AV2 is the solution identified by the HomePlug Alliance to achieve the improved data rate performance required by the new generation of multimedia applications without the need to install extra wires. Developed by industry-leading participants in the HomePlug AV Technical Working Group, the HomePlug AV2 technology provides Gigabit-class connection speeds over the existing AC wires within  home. It is designed to meet the market demands for the full set of future in-home networking connectivity. Moreover, HomePlug AV2 guarantees backward interoperability with other HomePlug systems. In this paper, the HomePlug AV2 system architecture is introduced and the technical details of the key features at both the PHY and MAC layers are described. The HomePlug AV2 performance is assessed, through simulations reproducing real home scenarios.', '-', 103, 16),
(7, 'Bio-Rad&#39;s Bio-Plex? suspension array system, xMAP technology overview', 'The Bio-Plex® system utilizes xMAP technology to permit the multiplexing of up to 100 different analytes. Multiplex analysis gives researchers the ability to look at analytes simultaneously providing more information from less sample volume in less time than traditional immunoassay methods. Similar to ELISA, xMAP utilizes an antibody sandwich for detection but differs from ELISA in capture substrate and detection method. Rather than a flat surface, Bio-Plex® assays make use of differentially detectable bead sets as a substrate capturing analytes in solution and employs fluorescent methods for detection. These bead sets identify the analytes and detection antibodies are used to measure the quantity of analyte. The use of differentially detectable beads enables the simultaneous identification and quantification of many analytes in the same sample.', '-', 205, 17),
(8, 'A review of robocasting technology', 'Robocasting is a freeform fabrication technique for dense ceramics and composites that is based on layer-wise deposition of highly loaded colloidal slurries. The process is essentially binderless with less than 1% organics and parts can be fabricated, dried, and completely sintered in less than 24 hours. This review will highlight materials developments for structural applications and modelling of slurry flow. Fabrication of preforms for alumina / metal composites will be discussed as well as techniques for multimaterial deposition in both graded structures and discrete placement of fugitive materials.', '-', 163, 19),
(9, 'What does robotics offer animal behaviour?', 'There is a growing body of robot-based research that makes a serious claim to be a new methodology for biology. Robots can be used as models of specific animal systems to test hypotheses regarding the control of behaviour. At levels from learning algorithms to specific dendritic circuits, implementing a proposed controller in a robotic device tests it against real environments in a way that is difficult to simulate. This often provides insight into the true nature of the problem. It also enforces complete specifications and combines bodies of data. Current work can sometimes be criticized for drawing unjustified conclusions given the limited evaluation and inevitable inaccuracies of robot models. Nevertheless, this approach has led to novel hypotheses for animal behaviour and seems likely to provide fruitful results in the future.', '-', 284, 29),
(10, 'Plant argonautes', 'ARGONAUTE (AGO) proteins are integral players in all known small RNA-directed regulatory pathways. Eukaryotes produce numerous types of small RNAs, such as microRNAs (miRNA), small interfering RNAs (siRNA), PIWI-interacting RNAs (piRNAs), scanRNAs and 21U-RNAs, and these RNA species associate with different types of AGO family members, such as AGO, PIWI and group 3 proteins. Small RNA-guided AGO proteins regulate gene expression at various levels, including internal genomic DNA sequence elimination (in ciliates), translational repression (animals), and RNA cleavage (all eukaryotes), which in some cases is followed by DNA methylation and chromatin remodeling. The plant model species Arabidopsis contains ten AGO proteins belonging to three phylogenetic clades. This review covers our current knowledge of plant AGO functions during miRNA- and siRNA-mediated regulation of development and stress responses, siRNA-mediated antiviral immune response, and siRNA-mediated regulation of chromatin structure and transposons.', '-', 702, 31),
(11, 'Plant cystatins', 'Plant cystatins have been the object of intense research since the publication of a first paper reporting their existence more than 20 years ago. These ubiquitous inhibitors of Cys  proteases play several important roles in plants, from the control of various physiological and cellular processes  in planta to the inhibition of exogenous Cys proteases secreted by herbivorous arthropods and pathogens to digest or colonize plant tissues. After an overview of current knowledge about the evolution, structure and inhibitory mechanism of plant cystatins, we review the different roles attributed to these proteins in plants. The potential of recombinant plant cystatins as effective pesticidal proteins in crop protection is also considered, as well as protein engineering approaches adopted over the years to improve their inhibitory potency and specificity towards Cys proteases of biotechnological interest.', '-', 207, 35),
(12, 'What happened to plant caspases?', 'The extent of conservation in the programmed cell death pathways that are activated in species belonging to different kingdoms is not clear. Caspases are key components of animal apoptosis; caspase activities are detected in both animal and plant cells. Yet, while animals have caspase genes, plants do not have orthologous sequences in their genomes. It is 10 years since the first caspase activity was reported in plants, and there are now at least eight caspase activities that have been measured in plant extracts using caspase substrates. Various caspase inhibitors can block many forms of plant programmed cell death, suggesting that caspase-like activities are required for completion of the process. Since plant metacaspases do not have caspase activities, a major challenge is to identify the plant proteases that are responsible for the caspase-like activities and to understand how they relate, if at all, to animal caspases. The protease vacuolar processing enzyme, a legumain, is responsible for the cleavage of caspase-1 synthetic substrate in plant extracts. Saspase, a serine protease, cleaves caspase-8 and some caspase-6 synthetic substrates. Possible scenarios that could explain why plants have caspase activities without caspases are discussed.', '-', 229, 37),
(13, 'The plant sulfolipid', 'This chapter describes plant sulfolipid. Sulfoquinovose and its glycosides, glyceryl sulfoquinovoside and the sulfolipid, comprise the most concentrated anionic sugar derivatives in plants. As salts of a very strong sulfonic acid, they are anionic under all conditions. Sulfolipid possesses an extremely hydrophyllic moiety and two fatty ester groups. This amphipathic molecule is expected to exhibit excellent surfactant properties. Its high concentration in the lamellar lipoprotein structures of plant chloroplasts undoubtedly is a result of such properties. Its role in sulfate reduction and carbohydrate metabolism may be related to its location and orientation at important interfaces in the photosynthetic apparatus. When large quantities of sulfolipid become available, they may provide effective substitutes for synthetic surfactants in medical and industrial applications, where metabolic degradation is essential for safe or effective use.', '-', 202, 40),
(14, 'Thoracic imaging tests for the diagnosis of COVID&#8208;19', 'Nine chest CT studies (2807 participants, 1139 (41%) cases) used the COVID‐19 Reporting and Data System (CO‐RADS) scoring system, which has five thresholds to define index test positivity. At a CO‐RADS threshold of 5 (7 studies), the sensitivity ranged from 41.5% to 77.9% and the pooled sensitivity was 67.0% (95% CI 56.4 to 76.2); the specificity ranged from 83.5% to 96.2%; and the pooled specificity was 91.3% (95% CI 87.6 to 94.0). At a CO‐RADS threshold of 4 (7 studies), the sensitivity ranged from 56.3% to 92.9% and the pooled sensitivity was 83.5% (95% CI 74.4 to 89.7); the specificity ranged from 77.2% to 90.4% and the pooled specificity was 83.6% (95% CI 80.5 to 86.4). ', '-', 171, 41),
(15, 'COVID-19 and multiorgan response', 'Since the outbreak and rapid spread of COVID-19 starting late December 2019, it has been apparent that disease prognosis has largely been influenced by multiorgan involvement. Comorbidities such as cardiovascular diseases have been the most common risk factors for severity and mortality. The hyperinflammatory response of the body, coupled with the plausible direct effects of severe acute respiratory syndrome on body-wide organs via angiotensin-converting enzyme 2, has been associated with complications of the disease. Acute respiratory distress syndrome, heart failure, renal failure, liver damage, shock, and multiorgan failure have precipitated death. Acknowledging the comorbidities and potential organ injuries throughout the course of COVID-19 is therefore crucial in the clinical management of patients. This paper aims to add onto the ever-emerging landscape of medical knowledge on COVID-19, encapsulating its multiorgan impact.', '-', 848, 44),
(16, 'Signs and symptoms to determine if a patient presenting in primary care or hospital outpatient settings has COVID&#8208;19', 'The clinical implications of SARS‐CoV‐2 infection are highly variable. Some people with SARS‐CoV‐2 infection remain asymptomatic, whilst the infection can cause mild to moderate COVID‐19 and COVID‐19 pneumonia in others. This can lead to some people requiring intensive care support and, in some cases, to death, especially in older adults. Symptoms such as fever, cough, or loss of smell or taste, and signs such as oxygen saturation are the first and most readily available diagnostic information. Such information could be used to either rule out COVID‐19, or select patients for further testing. This is an update of this review, the first version of which published in July 2020. ', '-', 449, 45),
(17, 'Routine laboratory testing to determine if a patient has COVID&#8208;19', 'We included 21 studies in this review, including 14,126 COVID‐19 patients and 56,585 non‐COVID‐19 patients in total. Studies evaluated a total of 67 different laboratory tests. Although we were interested in the diagnotic accuracy of routine tests for COVID‐19, the included studies used detection of SARS‐CoV‐2 infection through RT‐PCR as reference standard. There was considerable heterogeneity between tests, threshold values and the settings in which they were applied. For some tests a positive result was defined as a decrease compared to normal vaues, for other tests a positive result was defined as an increase, and for some tests both increase and decrease may have indicated test positivity. None of the studies had either low risk of bias on all domains or low concerns for applicability for all domains. Only three of the tests evaluated had a summary sensitivity and specificity over 50%. These were: increase in interleukin‐6, increase in C‐reactive protein and lymphocyte count decrease. ', '-', 49, 46),
(18, 'Environmental perspective of COVID-19', '•\n\nCOVID-19 has been declared as a global health emergency due to spread of corona virus.•\n\nTo prevent the transmission mask, surgical gloves and sanitizer were used.•\n\nIt has led to generation of massive amount of medical wastes in the environment.•\n\nMillions of people have been placed under lockdown to reduce the transmission.•\n\nReduction in economic activities and improved air and water quality across the globe.', '-', 666, 47),
(19, 'Treatment for COVID-19: An overview', 'Coronavirus disease 2019 (COVID-19) is an infectious disease caused by coronavirus-2 (SARS-CoV-2) that causes a severe acute respiratory syndrome, a characteristic hyperinflammatory response, vascular damage, microangiopathy, angiogenesis and widespread thrombosis. Four stages of COVID-19 have been identified: the first stage is characterised by upper respiratory tract infection; the second by the onset of dyspnoea and pneumonia; the third by a worsening clinical scenario dominated by a cytokine storm and the consequent hyperinflammatory state; and the fourth by death or recovery. Currently, no treatment can act specifically against the SARS-CoV-2 infection. Based on the pathological features and different clinical phases of COVID-19, particularly in patients with moderate to severe COVID-19, the classes of drugs used are antiviral agents, inflammation inhibitors/antirheumatic drugs, low molecular weight heparins, plasma, and hyperimmune immunoglobulins. During this emergency period of the COVID-19 outbreak, clinical researchers are using and testing a variety of possible treatments. Based on these premises, this review aims to discuss the most updated pharmacological treatments to effectively act against the SARS-CoV-2 infection and support researchers and clinicians in relation to any current and future developments in curing COVID-19 patients.', '-', 171, 49),
(20, 'Role of favipiravir in the treatment of COVID-19', '•\n\nFavipiravir is approved by some countries, including India, for COVID-19 treatment.•\n\nFavipiravir has shown rapid viral clearance and faster clinical improvement.•\n\nVarious treatment recommendations include favipiravir for COVID-19 treatment.•\n\nSeveral ongoing clinical trials will further substantiate favipiravir role.', '-', 200, 50),
(21, 'Climate change and marine plankton', 'Understanding how climate change will affect the planet is a key issue worldwide. Questions concerning the pace and impacts of climate change are thus central to many ecological and biogeochemical studies, and addressing the consequences of climate change is now high on the list of priorities for funding agencies. Here, we review the interactions between climate change and plankton communities, focusing on systematic changes in plankton community structure, abundance, distribution and phenology over recent decades. We examine the potential socioeconomic impacts of these plankton changes, such as the effects of bottom-up forcing on commercially exploited fish stocks (i.e. plankton as food for fish). We also consider the crucial roles that plankton might have in dictating the future pace of climate change via feedback mechanisms responding to elevated atmospheric CO2 levels. An important message emerges from this review: ongoing plankton monitoring programmes worldwide will act as sentinels to identify future changes in marine ecosystems.', '-', 1311, 51),
(22, 'Marine plankton food chains', '  Annual Reviews was founded in 1932 as a nonprofit scientific publisher to help    scientists cope with the ever-increasing volume of scientific research. Comprehensive,    authoritative, and critical reviews written by the world\'s leading scientists    are now published in twenty-six disciplines in the biological, physical, and    social sciences. According to the \"Impact Factor\" rankings of the Institute    for Scientific Information\'s Science Citation Index, each Annual Review ranks    at or near the top of its respective subject category. A searchable title and    author database and a collection of abstracts may be found at https://www.annualreviews.org//. The web site also    provides information and pricing for all printed volumes, online publications,    and reprint collections. ', '-', 534, 52),
(23, 'The structure and evolution of plankton communities', 'New understanding of the circulation of ancient oceans is not yet matched by progress in our understanding of their pelagic ecology, though it was the planktonic ecosystems that generated our offshore oil and gas reserves. Can we assume that present-day models of ecosystem function are also valid for ancient seas? This question is addressed by a study of over 4000 plankton samples to derive a comprehensive, global description of zooplankton community structure in modern oceans: this shows that copepods form only 50% of the biomass of all plankton, ranging from 70% in polar to 35% in tropical seas. Comparable figures are derived from 14 other taxonomic categories of zooplankton. For trophic groupings, the data indicate globally: geletinous predators — 14%; gelatinous herbivores — 4%; raptorial predators — 33%; macrofiltering herbivores — 20%; macrofiltering omnivores — 25%; and detritivores — 3%. A simple, idealized model for the modern pelagic ecosystem is derived from these percentages which indicates that metazooplankton are not the most important consumers of pico- and nano-plankton production which itself probably constitutes 90% of primary production in warm oceans.', '-', 219, 56),
(24, 'The peril of the plankton', 'The pelagic environment is characterized by unevenly distributed resources and risks. Such unpredictability presents adaptive challenges to diverse planktonic organisms including the larvae of benthic marine invertebrates. Estimates of mortality during planktonic development are highly variable, ranging from 0% to 100% per day. Predation is considered a significant source of this mortality, but what explains the variability in estimates of the mortality of marine invertebrate larvae? While differential exposure of larval prey to predators may explain these widely variable estimates, adaptations that reduce vulnerability of marine larvae to predators may also be important. Although there are excellent reviews of predation upon larvae and of larval mortality and defenses, nearly 15 years have elapsed since these topics were formally reviewed. Here, we highlight recent advances in understanding the behavioral, chemical, and morphological defenses that larvae possess and assess their effectiveness in reducing the risk of predation. While recent work confirms that larval mortality is generally high, it also demonstrates that larvae can reduce their risk of predation in several ways, including: (1) temporarily escaping the benthos during vulnerable early stages, (2) producing chemical compounds that reduce palatability, (3) possessing morphological defenses such as spines and shells, and (4) exhibiting induced defensive responses whereby larvae can alter their behavior, morphology, and life histories in the presence of predators. Taken together, these studies indicate that marine invertebrate larvae possess a sophisticated suite of defensive phenotypes that have allowed them to persist in the life cycle of benthic invertebrates for eons.', '-', 73, 58),
(25, 'Towards a resolution of &#39;the paradox of the plankton&#39;: A brief overview of the proposed mechanisms', 'In plankton ecology, it is a fundamental question as to how a large number of competing phytoplankton species coexist in marine ecosystems under a seemingly-limited variety of resources. This ever-green question was first proposed by Hutchinson [Hutchinson, G.E., 1961. The paradox of the plankton. Am. Nat. 95, 137–145] as ‘the paradox of the plankton’. Starting from Hutchinson [Hutchinson, G.E., 1961. The paradox of the plankton. Am. Nat. 95, 137–145], over more than four decades several investigators have put forward varieties of mechanisms for the extreme diversity of phytoplankton species. In this article, within the boundary of our knowledge, we review the literature of the proposed solutions and give a brief overview of the mechanisms proposed so far. The proposed mechanisms that we discuss mainly include spatial and temporal heterogeneity in physical and biological environment, externally imposed or self-generated spatial segregation, horizontal mesoscale turbulence of ocean characterized by coherent vortices, oscillation and chaos generated by several internal and external causes, stable coexistence and compensatory dynamics under fluctuating temperature in resource competition, and finally the role of toxin-producing phytoplankton in maintaining the coexistence and biodiversity of the overall plankton population that we have proposed recently. We find that, although the different mechanisms proposed so far is potentially applicable to specific ecosystems, a universally accepted theory for explaining plankton diversity in natural waters is still an unachieved goal.', '-', 163, 59);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `crawl`
--
ALTER TABLE `crawl`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `data`
--
ALTER TABLE `data`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `journals`
--
ALTER TABLE `journals`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `journal_data`
--
ALTER TABLE `journal_data`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_crawl` (`crawl_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `crawl`
--
ALTER TABLE `crawl`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- AUTO_INCREMENT for table `data`
--
ALTER TABLE `data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT for table `journals`
--
ALTER TABLE `journals`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT for table `journal_data`
--
ALTER TABLE `journal_data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `journal_data`
--
ALTER TABLE `journal_data`
  ADD CONSTRAINT `fk_crawl` FOREIGN KEY (`crawl_id`) REFERENCES `crawl` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
